# Dockerfile

FROM phusion/passenger-ruby23

MAINTAINER bhagyesh.raut@joshsoftware.com

# Set correct environment variables.
ENV HOME /root

RUN gem install bundler

RUN bash -lc 'rvm install ruby-2.3.3'
RUN bash -lc 'rvm --default use ruby-2.3.3'

RUN apt-get install -y libmagick++-dev
RUN apt-get install -y tzdata


# Install bundle of gems
WORKDIR /tmp
ADD Gemfile /tmp/
ADD Gemfile.lock /tmp/
RUN bundle install

# Add the Rails app
ADD . /home/app/webapp
RUN chown -R app:app /home/app/webapp

WORKDIR /home/app/webapp
# Clean up APT and bundler when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /home/app/webapp

CMD [ "bundle", "exec", "sidekiq --environment staging -C config/sidekiq.yml"]

