# Dockerfile

FROM phusion/passenger-ruby23

MAINTAINER bhagyesh.raut@joshsoftware.com

# Set correct environment variables.
ENV HOME /root

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

# Expose Nginx HTTP service
EXPOSE 80

# Start Nginx / Passenger
RUN rm -f /etc/service/nginx/down

# Remove the default site
RUN rm /etc/nginx/sites-enabled/default
RUN rm /etc/nginx/sites-available/default

# Add the nginx site and config
ADD default.conf /etc/nginx/sites-enabled/webapp.conf

RUN gem install bundler

RUN bash -lc 'rvm install ruby-2.3.3'
RUN bash -lc 'rvm --default use ruby-2.3.3'

RUN apt-get install -y libmagick++-dev
RUN apt-get install -y tzdata


# Install bundle of gems
WORKDIR /tmp
ADD Gemfile /tmp/
ADD Gemfile.lock /tmp/
RUN bundle install

# Add the Rails app
ADD . /home/app/webapp
RUN chown -R app:app /home/app/webapp

# Clean up APT and bundler when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
ENV RAILS_ENV=staging
